language: python
python:
  - "2.7"
cache:
    directories:
        - "~/.platformio"
addons:
  apt_packages:
    - lib32bz2-1.0
    - lib32ncurses5
    - lib32z1
    
before_script:
  - wget https://github.com/Infineon/Assets/releases/download/current/gcc-arm-none-eabi-5_4-2016q3-20160926-linux.-d-.tar.bz2 -O /tmp/gcc-arm-none-eabi.tar.bz2
  - tar -xjf /tmp/gcc-arm-none-eabi.tar.bz2
  - export PATH=$PATH:$PWD/gcc-arm-none-eabi-5_4-2016q3/bin/

env:
  # defining this variable creates multiple jobs in Travis
  # TODO keep these examples up-to-date with the ones in the core
  - PLATFORMIO_PROJECT_DIR=examples/arduino-blink
  - PLATFORMIO_PROJECT_DIR=examples/arduino-wire/master_reader
  - PLATFORMIO_PROJECT_DIR=examples/arduino-wire/master_writer
  - PLATFORMIO_PROJECT_DIR=examples/arduino-wire/slave_receiver
  - PLATFORMIO_PROJECT_DIR=examples/arduino-wire/slave_sender
  - PLATFORMIO_PROJECT_DIR=examples/device-control/DieTemperatureMeasurement
  - PLATFORMIO_PROJECT_DIR=examples/device-control/HeapMemoryMeasurement
  - PLATFORMIO_PROJECT_DIR=examples/device-control/SleepModeXMC1100
  - PLATFORMIO_PROJECT_DIR=examples/device-control/SleepModeXMC4700
  - PLATFORMIO_PROJECT_DIR=examples/device-control/StackMemoryMeasurement
  - PLATFORMIO_PROJECT_DIR=examples/ifx9201/MotorControl
  - PLATFORMIO_PROJECT_DIR=examples/rtc/AlarmRTC
  - PLATFORMIO_PROJECT_DIR=examples/rtc/HibernateRTCAlarm
  - PLATFORMIO_PROJECT_DIR=examples/rtc/SimpleRTC
  - PLATFORMIO_PROJECT_DIR=examples/spi/BarometricPressureSensor
  - PLATFORMIO_PROJECT_DIR=examples/spi/DigitalPotControl
  - PLATFORMIO_PROJECT_DIR=examples/ultrasonic/betterecho
  - PLATFORMIO_PROJECT_DIR=examples/ultrasonic/simple-echo

install:
  - zip -r /tmp/framework-arduinoxmc.zip ./arm  
  - git clone https://github.com/Infineon/platformio-infineonxmc.git /tmp/builder
  - cd /tmp/builder
  - platform_json=$(<platform.json)
  - rm platform.json
  - jq '.packages."framework-arduinoxmc".version = "file:///tmp/framework-arduinoxmc.zip"' <<<"$platform_json" > platform.json

  - pip install -U https://github.com/platformio/platformio/archive/develop.zip
  - platformio platform install -f file://. --without-package=uploader

script:
  - platformio run -d $PLATFORMIO_PROJECT_DIR