# code-quality:
#     - source-code-quality-clang-tidy
#     - source-code-quality-cppcheck
#     - test-code-quality-clang-tidy
#     - test-code-quality-cppcheck
#     - code-quality-clang-format
#     - code-quality-black-format

# compile:
#     - compile-psoc6-cy8ckit_062s2_ai


unit-test:
   - unit-test-digital-io-4700
   - unit-test-tone-4700
   - unit-test-iic-pingpong-4700
   - unit-test-interrupts-4700
   - unit-test-random-4700
   - unit-test-uart-connected2-4700
   - unit-test-spi-pingpong-4700
   - unit-test-analog-io-pwm-4700
   - unit-test-pulse-4700
   - unit-test-time-4700
   - unit-test-iic-4700
   - unit-test-analog-io-adc-4700
   - unit-test-analog-io-dac-4700
   - unit-test-uart-4700
   - unit-test-spi-single-pingpong-4700
   - unit-test-onewire-DS18x20-4700
  #  - unit-test-can-1400-2go


  #  - unit-test-digital-io-1400
  #  - unit-test-tone-1400
  #  - unit-test-interrupts-1400
  #  - unit-test-random-1400
  #  - unit-test-time-1400
  #  - unit-test-analog-io-pwm-1400
  #  - unit-test-analog-io-adc-1400