name: HIL Checks

on:
  pull_request:

jobs:
  makers-devops:
    uses: Infineon/makers-devops/.github/workflows/hil_checks.yml@main
    with:
      project-yaml: config/project.yml
      user-yaml: config/user.yml
    secrets: inherit