name: XMC-for-Arduino Release Automation

on:
  release:
    types: published
  push:
    tags: 
      - 'v*.*.*'
      - 'V*.*.*'
jobs:
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/V')
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Build release changelog
      id: build_changelog
      uses: mikepenz/release-changelog-builder-action@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build release assets
      run: |
        cd .github/scripts
        echo "Tag name : ${{ github.ref_name }}"
        python release.py build-release ${{ github.ref_name }}

    - name: Upload assets
      uses: softprops/action-gh-release@v1
      with:
        name: XMC for Arduino ${{  github.ref_name  }}
        files: |
          pkg_build/*.zip
          pkg_build/package_infineon_index.json
        body: ${{steps.build_changelog.outputs.changelog}}